### ISSUE TITLE
Create / Edit Product - It’s impossible to enter decimal amounts in the Value (USD) slot (duplicate)

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#119] opened 2020-05-08 15:19 UTC

**Comment by nimsarr** [comment] 2020-05-19 00:21
Duplicate of https://github.com/tulip/ppe-logistics/issues/162

**Closed as completed by nimsarr** 2020-05-19 00:21 UTC
Labels: bug

**Comment by jackkrooss** [comment] 2020-05-19 00:30
yup, thanks

**Comment by jackkrooss** [comment] 2020-05-19 00:31
NO ACTUALLY, different.

**Comment by jackkrooss** [comment] 2020-05-19 00:34
Decimal $$ is self explanatory, but decimal product means that you can have
a fraction of a product used for a child product. Example is that you have
a spool of elastic that you use for headbands. The spool is 200 feet long.
You use 2 feet of elastic per headband. So you use .01 elastic spools per
headband.

**Comment by jackkrooss** [comment] 2020-05-19 00:44
Never mind, Simon was correct this is a duplicated. Fractional BOM stuff is
addressed in #163
